# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Interface(QtWidgets.QMainWindow):
    def __init__(self, *, version:str):
        super().__init__()
        if not version.lower().startswith('v'):
            version = 'V' + version
        self.__version:str = version
    
    def setupUi(self):
        self.setObjectName("Dialog")
        self.resize(524, 370)
        
        self.Janelas = QtWidgets.QStackedWidget(self)
        self.Janelas.setGeometry(QtCore.QRect(10, 10, 501, 351))
        self.Janelas.setObjectName("Janelas")
        
        self.janela_1 = QtWidgets.QWidget()
        self.janela_1.setObjectName("janela_1")
        
        self.janela_1_widget_calendario = QtWidgets.QCalendarWidget(self.janela_1)
        self.janela_1_widget_calendario.setGeometry(QtCore.QRect(80, 10, 341, 211))
        self.janela_1_widget_calendario.setObjectName("janela_1_widget_calendario")
        
        self.janela_1_bt_extrair = QtWidgets.QPushButton(self.janela_1)
        self.janela_1_bt_extrair.setGeometry(QtCore.QRect(300, 240, 100, 31))
        self.janela_1_bt_extrair.setObjectName("janela_1_bt_extrairRelatorio")
        
        self.janela_1_bt_voltar = QtWidgets.QPushButton(self.janela_1)
        self.janela_1_bt_voltar.setGeometry(QtCore.QRect(130, 240, 100, 31))
        self.janela_1_bt_voltar.setObjectName("janela_1_bt_voltar")
        self.janela_1_bt_voltar.clicked.connect(self.ir_pagina_2)
        
        
        self.janela_1_label_textoInfor = QtWidgets.QLabel(self.janela_1)
        self.janela_1_label_textoInfor.setGeometry(QtCore.QRect(50, 290, 391, 51))
        self.janela_1_label_textoInfor.setAlignment(QtCore.Qt.AlignCenter) #type: ignore
        self.janela_1_label_textoInfor.setObjectName("janela_1_label_textoInfor")
        
        self.Janelas.addWidget(self.janela_1)
        
        self.janela_2 = QtWidgets.QWidget()
        self.janela_2.setObjectName("janela_2")
        
        self.janela_2_bt_extrairRelatorio = QtWidgets.QPushButton(self.janela_2)
        self.janela_2_bt_extrairRelatorio.setGeometry(QtCore.QRect(130, 100, 241, 31))
        self.janela_2_bt_extrairRelatorio.setObjectName("janela_2_bt_extrairRelatorio")
        self.janela_2_bt_extrairRelatorio.clicked.connect(self.ir_pagina_1)
        
        
        self.Janelas.addWidget(self.janela_2)

        self.retranslateUi()
        self.Janelas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", f"Partes Relacionadas {self.__version}"))
        self.janela_1_bt_extrair.setText(_translate("Dialog", "Extrair"))
        self.janela_1_bt_voltar.setText(_translate("Dialog", "Voltar"))
        self.janela_1_label_textoInfor.setText(_translate("Dialog", ""))
        self.janela_2_bt_extrairRelatorio.setText(_translate("Dialog", "Extrair Relatorio"))
        
    def ir_pagina_1(self):
        self.Janelas.setCurrentIndex(0)
        
    def ir_pagina_2(self):
        self.Janelas.setCurrentIndex(1)
    
    def openFileNameDialog(self):
        options = QtWidgets.QFileDialog.Options()
        defaultFileName = "Batch.xlsx"
        fileName, _ = QtWidgets.QFileDialog.getSaveFileName(self, "Salvar Arquivo", defaultFileName, "Planilhas Excel (*.xlsx)", options=options)
        return fileName


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Interface(version="1.0")
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
